/**
 * Finova API
 *
 * Contact: dev@finova.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponseDto { 
    /**
     * The unique identifier of the user
     */
    id: string;
    /**
     * The email address of the user
     */
    email: string;
}

