/**
 * Finova API
 *
 * Contact: dev@finova.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginDto { 
    /**
     * The email address of the user
     */
    email: string;
    /**
     * The password of the user
     */
    password: string;
}

