/**
 * Finova API
 *
 * Contact: dev@finova.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDto { 
    /**
     * User email address
     */
    email: string;
    /**
     * User password (min 8 chars)
     */
    password: string;
}

