/**
 * Finova API
 *
 * Contact: dev@finova.mx
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserResponseDto { 
    /**
     * The unique identifier of the user
     */
    id: string;
    /**
     * The email address of the user
     */
    email: string;
    /**
     * Global spending limit preference
     */
    globalSpendingLimitPreference?: object;
    /**
     * User creation date
     */
    createdAt: string;
    /**
     * User last update date
     */
    updatedAt: string;
}

